export const CREATE_POST = 'CREATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const GET_POSTS = 'GET_POSTS'
export const UPDATE_POST = 'UPDATE_POST'

export const ADD_COMMENT_TO_POST = 'ADD_COMMENT_TO_POST'
export const DELETE_COMMENT_FROM_POST = 'DELETE_COMMENT_FROM_POST'
export const GET_COMMENTS_FROM_POST = 'GET_COMMENTS_FROM_POST'

export const TOGGLE_POST_LOADER = 'TOGGLE_POST_LOADER'
export const ADD_POST = 'ADD_POST'
